version: "3.7"

services:
  react:
    container_name: spot_react
    build: ../.
    ports:
        - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_ADDRESS=${VITE_API_BASE_ADDRESS}
    volumes:
      - '../:/app'
      - '/app/node_modules'
    networks:
      - kleeant_network

networks:
  kleeant_network: